version: '2'
services:
    ninecat-app:
        image: ninecat
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ninecat-postgresql:5432/ninecat
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ninecat-postgresql:
        extends:
            file: postgresql.yml
            service: ninecat-postgresql
